### valor inicial

GET http://localhost:2020

### ver version

GET http://localhost:2020/api

### ver users

GET http://localhost:2020/api/users

### crear user

POST http://localhost:2020/api/users/register
Content-Type: application/json

{
    "username": "elisa",
    "password": "chau124",
    "email": "sordinicaro12@gmail.com"
}


### login
POST http://localhost:2020/api/login 
Content-Type: application/json
{
"username": "tativega",
"password": "test123"
}
### Logout
DELETE http://localhost:2020/api/logout
Content-Type: application/json

{
  "username": "tativega",
   "token": "123"
}